let myMap = L.map("map").setView([39.0997, -94.5786], 4);

L.tileLayer('https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png', {
	attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors &copy; <a href="https://carto.com/attributions">CARTO</a>',
	maxZoom: 20
}).addTo(myMap);

let solMarker = L.marker([40.6892, -74.0445]).addTo(myMap);
let gcMarker = L.marker([36.2679, -112.3535]).addTo(myMap);
let hwsMarker = L.marker([34.1341, -118.3215]).addTo(myMap); 
let nfMarker = L.marker([43.0828, -79.0742]).addTo(myMap);
let whMarker = L.marker([38.8977, -77.0365]).addTo(myMap);
let mvuMarker = L.marker([37.0045, -110.1732]).addTo(myMap);
let wdwMarker = L.marker([28.3772, -81.5707]).addTo(myMap);
let ggbMarker = L.marker([37.8199, -122.4786]).addTo(myMap);
let cgMarker = L.marker([41.8827, -87.6233]).addTo(myMap);
let mrMarker = L.marker([43.8803, -103.4538]).addTo(myMap);
let gaMarker = L.marker([38.6251, -90.1868]).addTo(myMap);
let snMarker = L.marker([47.6205, -122.3493]).addTo(myMap);
let ynpMarker = L.marker([37.8651, -119.5383]).addTo(myMap);
let hdMarker = L.marker([36.0161, -114.7377]).addTo(myMap);
let glMarker = L.marker([35.0477, -90.0260]).addTo(myMap);
let dtMarker = L.marker([44.5902, -104.7146]).addTo(myMap);
let rcMarker = L.marker([42.3293, -83.0398]).addTo(myMap);
let rhfMarker = L.marker([41.5085, -81.6954]).addTo(myMap);
let gsmMarker = L.marker([35.6131, -83.5532]).addTo(myMap);
let lhMarker = L.marker([36.0955, -115.1761]).addTo(myMap);
let lbMarker = L.marker([39.9496, -75.1503]).addTo(myMap);
let ynMarker = L.marker([44.4280, -110.5885]).addTo(myMap);
let gnpMarker = L.marker([48.7596, -113.7870]).addTo(myMap);
let blnpMarker = L.marker([43.8554, -102.3397]).addTo(myMap);
let dlpMarker = L.marker([33.8121, -117.9190]).addTo(myMap);
let disMarker = L.marker([29.1847, -81.0683]).addTo(myMap);
let kscMarker = L.marker([28.5744, -80.6520]).addTo(myMap);
let ccsMarker = L.marker([41.6688, -70.2962]).addTo(myMap);
let hsnpMarker = L.marker([34.5269, -93.0691]).addTo(myMap);
let gobMarker = L.marker([34.1184, -118.3004]).addTo(myMap);
let vnmpMarker = L.marker([32.3398, -90.8510]).addTo(myMap);
let jsMarker = L.marker([29.9574, -90.0629]).addTo(myMap);
let kwfMarker = L.marker([24.5551, -81.7800]).addTo(myMap);
let crMarker = L.marker([41.4213, -103.2054]).addTo(myMap);
let lmMarker = L.marker([43.4501, -87.2220]).addTo(myMap);
let safMarker = L.marker([29.8922, -81.3139]).addTo(myMap);
let clMarker = L.marker([42.9446, -122.1090]).addTo(myMap);
let cpoMarker = L.marker([41.4822, -82.6835]).addTo(myMap);
let mbfMarker = L.marker([25.7907, -80.1300]).addTo(myMap);
let pncMarker = L.marker([40.4475, -80.0072]).addTo(myMap);
let mbMarker = L.marker([33.6954, -78.8802]).addTo(myMap);
let obMarker = L.marker([35.5585, -75.4665]).addTo(myMap);
let rmnpMarker = L.marker([40.3428, -105.6836]).addTo(myMap);
let taMarker = L.marker([29.4260, -98.4861]).addTo(myMap);
let wsnpMarker = L.marker([32.7872, -106.3257]).addTo(myMap);
let ocnmMarker = L.marker([35.4727, -97.5172]).addTo(myMap);
let kcscMarker = L.marker([38.0355, -97.5517]).addTo(myMap);
let bdspMarker = L.marker([42.5436, -115.4235]).addTo(myMap);
let trnpMarker = L.marker([46.9790, -103.5387]).addTo(myMap);
let moaMarker = L.marker([44.8549, -93.2422]).addTo(myMap);
let mrmaMarker = L.marker([42.4967, -90.6606]).addTo(myMap);
let fwczMarker = L.marker([41.1038, -85.1527]).addTo(myMap);
let imsMarker = L.marker([39.7903, -86.2337]).addTo(myMap);
let cgkMarker = L.marker([36.6148, -83.6695]).addTo(myMap);
let kdMarker = L.marker([38.2053, -85.7712]).addTo(myMap);
let usrcMarker = L.marker([34.7068, -86.6525]).addTo(myMap);
let smspMarker = L.marker([33.8052, -84.1451]).addTo(myMap);
let lfMarker = L.marker([44.5013, -88.0622]).addTo(myMap);
let mbmMarker = L.marker([45.8174, -84.7278]).addTo(myMap);
let nrgbMarker = L.marker([38.0693, -81.0829]).addTo(myMap);
let hfMarker = L.marker([39.3254, -77.7389]).addTo(myMap);
let hpMarker = L.marker([40.2888, -76.6547]).addTo(myMap);
let snpMarker = L.marker([38.4755, -78.4535]).addTo(myMap);
let bgMarker = L.marker([37.2337, -76.6440]).addTo(myMap);
let lcMarker = L.marker([38.6645, -78.4834]).addTo(myMap);
let wfpMarker = L.marker([44.4795, -73.2220]).addTo(myMap);
let lwMarker = L.marker([43.5686, -71.2163]).addTo(myMap);
let msmMarker = L.marker([41.3612, -71.9639]).addTo(myMap);
let anpMarker = L.marker([44.3386, -68.2733]).addTo(myMap);
let kfnpMarker = L.marker([59.8487, -150.1879]).addTo(myMap);
let mgvcMarker = L.marker([58.4171, -134.5457]).addTo(myMap);
let dnpMarker = L.marker([63.1148, -151.1926]).addTo(myMap);
let gbnpMarker = L.marker([58.6658, -136.9002]).addTo(myMap);
let hgcMarker = L.marker([60.3139, -139.3708]).addTo(myMap);
let pbaMarker = L.marker([71.3875, -156.4811]).addTo(myMap);
let awccMarker = L.marker([60.8247, -148.9830]).addTo(myMap);
let mwMarker = L.marker([44.2706, -71.3033]).addTo(myMap);
let ppMarker = L.marker([38.8409, -105.0423]).addTo(myMap);
let phMarker = L.marker([21.3665, -157.9368]).addTo(myMap);
let dhsmMarker = L.marker([21.2638, -157.8041]).addTo(myMap);
let vnpMarker = L.marker([19.4964, -155.4662]).addTo(myMap);

solMarker.bindPopup("<img src=img/liberty.jpg style=width:100%;><b>Statue of Liberty - New York City, New York</b>");
gcMarker.bindPopup("<img src=img/grand.jpg style=width:100%;><b>Grand Canyon - Arizona</b>");
hwsMarker.bindPopup("<img src=img/hollywood.jpg style=width:100%;><b>Hollywood Sign - Hollywood California</b>");
nfMarker.bindPopup("<img src=img/niagra.jpg style=width:100%;><b>Niagra Falls - Buffalo, New York</b>");
whMarker.bindPopup("<img src=img/white.jpg style=width:100%;><b>The White House - Washington, D.C.</b>");
mvuMarker.bindPopup("<img src=img/valley.jpg style=width:100%;><b>Monument Valley - Utah</b>");
wdwMarker.bindPopup("<img src=img/disney.jpg style=width:100%;><b>Walt Disney World - Orlando, Florida</b>");
ggbMarker.bindPopup("<img src=img/golden.jpg style=width:100%;><b>Golden Gate Bridge - San Francisco, California</b>");
cgMarker.bindPopup("<img src=img/cloud.jpg style=width:100%;><b>Cloud Gate - Chicago, Illinois</b>");
mrMarker.bindPopup("<img src=img/rushmore.jpg style=width:100%;><b>Mount Rushmore - Keystone, South Dakota</b>");
gaMarker.bindPopup("<img src=img/arch.jpg style=width:100%;><b>Gateway Arch - St.Louis, Missouri</b>");
snMarker.bindPopup("<img src=img/needle.jpg style=width:100%;><b>Seattle Space Needle - Seattle, Washington</b>");
ynpMarker.bindPopup("<img src=img/yosemite.jpg style=width:100%;><b>Yosemite National Park - California</b>");
hdMarker.bindPopup("<img src=img/hoover.jpg style=width:100%;><b>Hoover Dam - Nevada</b>");
glMarker.bindPopup("<img src=img/graceland.jpg style=width:100%;><b>Graceland - Memphis, Tennessee</b>");
dtMarker.bindPopup("<img src=img/devilstower.jpg style=width:100%;><b>Devils Tower - Wyoming</b>");
rcMarker.bindPopup("<img src=img/renaissance.jpg style=width:100%;><b>Renaissance Center - Detroit Michigan</b>");
rhfMarker.bindPopup("<img src=img/rock.jpg style=width:100%;><b>Rock and Roll Hall of Fame - Cleveland, Ohio</b>");
gsmMarker.bindPopup("<img src=img/smokies.jpg style=width:100%;><b>The Great Smoky Mountains - North Carolina and Tennessee</b>");
lhMarker.bindPopup("<img src=img/luxor.jpg style=width:100%;><b>Luxor Hotel and Casino - Las Vegas, Nevada</b>");
lbMarker.bindPopup("<img src=img/bell.jpg style=width:100%;><b>Liberty Bell - Philadelphia, Pennsylvania</b>");
ynMarker.bindPopup("<img src=img/yellowstone.jpg style=width:100%;><b>Yellowstone National Park - Wyoming</b>");
gnpMarker.bindPopup("<img src=img/glacier.jpg style=width:100%;><b>Glacier National Park - Montana</b>");
blnpMarker.bindPopup("<img src=img/badlands.jpg style=width:100%;><b>Badlands National Park - South Dakota</b>");
dlpMarker.bindPopup("<img src=img/disneyland.jpg style=width:100%;><b>Disneyland Park - Anaheim, California</b>");
disMarker.bindPopup("<img src=img/daytona.jpg style=width:100%;><b>Daytona International Speedway - Daytona, Florida</b>");
kscMarker.bindPopup("<img src=img/kennedy.jpg style=width:100%;><b>Kennedy Space Center - Merritt Island, Florida</b>");
ccsMarker.bindPopup("<img src=img/capecod.jpg style=width:100%;><b>Cape Cod National Seashore - Massachusetts</b>");
hsnpMarker.bindPopup("<img src=img/springs.jpg style=width:100%;><b>Hot Springs National Park - Arkansas</b>");
gobMarker.bindPopup("<img src=img/griffith.jpg style=width:100%;><b>Griffith Observatory - Los Angeles, California</b>");
vnmpMarker.bindPopup("<img src=img/vicksburg.jpg style=width:100%;><b>Vicksburg National Military Park - Vicksburg, Mississippi</b>");
jsMarker.bindPopup("<img src=img/jackson.jpg style=width:100%;><b>Jackson Square - New Orleans, Louisiana</b>");
kwfMarker.bindPopup("<img src=img/keywest.jpg style=width:100%;><b>KeyWest - Southern Most City in US, Florida</b>");
crMarker.bindPopup("<img src=img/chimney.jpg style=width:100%;><b>Chimney Rock - Nebraska</b>");
lmMarker.bindPopup("<img src=img/michigan.jpg style=width:100%;><b>Lake Michigan - Great Lakes, United States</b>");
safMarker.bindPopup("<img src=img/augustine.jpg style=width:100%;><b>Saint Augustine - City in Florida</b>");
clMarker.bindPopup("<img src=img/crater.jpg style=width:100%;><b>Crater Lake - Oregon</b>");
cpoMarker.bindPopup("<img src=img/cedar.jpg style=width:100%;><b>Cedar Point Amusement Park - Sandusky, Ohio</b>");
mbfMarker.bindPopup("<img src=img/miami.jpg style=width:100%;><b>Miami Beach - Miami, Florida</b>");
pncMarker.bindPopup("<img src=img/pnc.jpg style=width:100%;><b>PNC Park - Pittsburgh, Pennsylvania</b>");
mbMarker.bindPopup("<img src=img/myrtle.jpg style=width:100%;><b>Myrtle Beach - Myrtle Beach, South Carolina")
obMarker.bindPopup("<img src=img/outerbanks.jpg style=width:100%;><b>The Outer Banks - North Carolina</b>");
rmnpMarker.bindPopup("<img src=img/rockies.jpg style=width:100%;><b>Rocky Mountain National Park - Colorado</b>");
taMarker.bindPopup("<img src=img/alamo.jpg style=width:100%;><b>The Alamo - San Antonio Texas</b>");
wsnpMarker.bindPopup("<img src=img/sands.jpg style=width:100%;><b>White Sands National Park - New Mexico</b>");
ocnmMarker.bindPopup("<img src=img/memorial.jpg style=width:100%;><b>Oklahoma City National Memorial - Oklahoma City, Oklahoma</b>");
kcscMarker.bindPopup("<img src=img/cosmos.jpg style=width:100%;><b>Kansas Cosmosphere and Space Center - Hutchinson, Kansas</b>");
bdspMarker.bindPopup("<img src=img/bruneau.jpg style=width:100%;><b>Bruneau Sand Dunes State Park - Idaho</b>");
trnpMarker.bindPopup("<img src=img/theodore.jpg style=width:100%;><b>Theodore Roosevelt National Park - North Dakota</b>");
moaMarker.bindPopup("<img src=img/mall.jpg style=width:100%;><b>Mall of America - Bloomington, Minnesota");
mrmaMarker.bindPopup("<img src=img/museum.jpg style=width:100%;><b>National Mississippi River Museum and Aquarium - Dubuque, Iowa");
fwczMarker.bindPopup("<img src=img/zoo.jpg style=width:100%;><b>Fort Wayne Children's Zoo - Fort Wayne, Indiana</b>");
imsMarker.bindPopup("<img src=img/speedway.jpg style=width:100%;><b>Indianapolis Motor Speedway - Indianapolis Indiana</b>");
cgkMarker.bindPopup("<img src=img/gap.jpg style=width:100%;><b>Cumberland Gap National Historical Park - Middlesboro, Kentucky</b>");
kdMarker.bindPopup("<img src=img/derby.jpg style=width:100%;><b>Kentucky Derby - Louisville, Kentucky</b>");
usrcMarker.bindPopup("<img src=img/space.jpg style=width:100%;><b>U.S. Space and Rocket Center - Huntsville, Alabama</b>");
smspMarker.bindPopup("<img src=img/stone.jpg style=width:100%;><b>Stone Mountain Park - Stone Mountain, Georgia</b>"); 
lfMarker.bindPopup("<img src=img/lambeau.jpg style=width:100%;><b>Lambeau Field - Green Bay, Wisconsin</b>");
mbmMarker.bindPopup("<img src=img/bridge.jpg style=width:100%;><b>Mackinac Bridge - Michigan</b>");
nrgbMarker.bindPopup("<img src=img/gorge.jpg style=width:100%;><b>New River Gorge Bridge - West Virginia</b>");
hfMarker.bindPopup("<img src=img/ferry.jpg style=width:100%;><b>Harpers Ferry - West Virginia</b>");
hpMarker.bindPopup("<img src=img/hershey.jpg style=width:100%;></b>Hershey Park - Hershey, Pennsylvania</b>");
snpMarker.bindPopup("<img src=img/shenandoah.jpg style=width:100%;><b>Shenandoah National Park - Virginia</b>");
bgMarker.bindPopup("<img src=img/busch.jpg style=width:100%;><b>Busch Gardens - Williamsburg, Virginia</b>");
lcMarker.bindPopup("<img src=img/luray.jpg style=width:100%;><b>Luray Caverns - Luray, Virginia</b>");
wfpMarker.bindPopup("<img src=img/waterfront.jpg style=width:100%;><b>Waterfront Park - Burlington, Vermont</b>");
lwMarker.bindPopup("<img src=img/lake.jpg style=width:100%;><b>Lake Winnipesaukee - New Hampshire</b>");
msmMarker.bindPopup("<img src=img/mystic.jpg style=width:100%;><b>Mystic Seaport Museum - Mystic, Connecticut</b>");
anpMarker.bindPopup("<img src=img/acadia.jpg style=width:100%;><b>Acadia National Park - Maine</b>");
kfnpMarker.bindPopup("<img src=img/kenai.jpg style=width:100%;><b>Kenai Fjords National Park - Alaska</b>");
mgvcMarker.bindPopup("<img src=img/mendenhall.jpg style=width:100%;><b>Mendenhall Glacier Visitor Center - Juneau, Alaska</b>");
dnpMarker.bindPopup("<img src=img/denali.jpg style=width:100%;><b>Denali National Park and Preserve - Alaska</b>");
gbnpMarker.bindPopup("<img src=img/glacierbay.jpg style=width:100%;><b>Glacier Bay National Park and Preserve - Alaska</b>");
hgcMarker.bindPopup("<img src=img/hubbard.jpg style=width:100%;><b>Hubbard Glacier - Alaska</b>");
pbaMarker.bindPopup("<img src=img/barrow.jpg style=width:100%;><b>Point Barrow - Alaska</b>");
awccMarker.bindPopup("<img src=img/conservation.jpg style=width:100%;><b>Alaska Wildlife Conservation Center - Girdwood, Alaska</b>");
mwMarker.bindPopup("<img src=img/washington.jpg style=width:100%;><b>Mount Washington - New Hampshire</b>");
ppMarker.bindPopup("<img src=img/pikes.jpg style=width:100%;><b>Pikes Peak - Colorado</b>");
phMarker.bindPopup("<img src=img/pearl.jpg style=width:100%;><b>Pearl Harbor - O'ahu, Territory of Hawaii</b>");
dhsmMarker.bindPopup("<img src=img/diamond.jpg style=width:100%;><b>Diamond Head State Monument - Honolulu, Hawaii</b>");
vnpMarker.bindPopup("<img src=img/volcanoes.jpg style=width:100%;><b>Hawaii Volcanoes National Park - Hawaii</b>");





